import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

import {
  checkProtectedBootstrapInclude,
  renderProtectedBootstrapInclude,
  writeProtectedBootstrapInclude,
} from '../../scripts/windows-protected-bootstrap-generator.mjs';

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe('Windows protected bootstrap generator', () => {
  it('renders canonical deterministic bytes for LF and CRLF source', () => {
    const lf = "$value = 'reviewed'\nexit 0\n";
    const first = renderProtectedBootstrapInclude(lf);
    const second = renderProtectedBootstrapInclude(lf.replaceAll('\n', '\r\n'));

    expect(second).toBe(first);
    expect(first).toMatch(
      /^; Generated by scripts\/windows-protected-bootstrap-generator\.mjs --write\.\n/u,
    );
    expect(first.endsWith('\n')).toBe(true);
    expect(first.match(/TALKING_QUILL_PROTECTED_BOOTSTRAP_PAYLOAD/gu)).toHaveLength(1);
    expect(renderProtectedBootstrapInclude(`${lf}# changed\n`)).not.toBe(first);
  });

  it('writes explicitly and rejects stale, malformed, or extra generated bytes in check mode', async () => {
    await mkdir(resolve('tmp'), { recursive: true });
    const root = await mkdtemp(resolve('tmp', 'bootstrap-generator-'));
    roots.push(root);
    const sourcePath = join(root, 'bootstrap.ps1');
    const includePath = join(root, 'bootstrap.nsh');
    await writeFile(sourcePath, "$value = 'reviewed'\r\nexit 0\r\n", 'utf8');

    const written = await writeProtectedBootstrapInclude({ sourcePath, includePath });
    const beforeCheck = await readFile(includePath);
    await expect(checkProtectedBootstrapInclude({ sourcePath, includePath })).resolves.toBe(
      written,
    );
    expect(await readFile(includePath)).toEqual(beforeCheck);

    await writeFile(includePath, `${written}; extra\n`, 'utf8');
    await expect(checkProtectedBootstrapInclude({ sourcePath, includePath })).rejects.toThrow(
      'pnpm nsis:bootstrap:write',
    );

    await writeFile(includePath, '!define TALKING_QUILL_PROTECTED_BOOTSTRAP_PAYLOAD "bad"\n');
    await expect(checkProtectedBootstrapInclude({ sourcePath, includePath })).rejects.toThrow(
      'Static protected bootstrap payload is stale',
    );

    await writeFile(includePath, written, 'utf8');
    await writeFile(sourcePath, "$value = 'mutated'\nexit 0\n", 'utf8');
    await expect(checkProtectedBootstrapInclude({ sourcePath, includePath })).rejects.toThrow(
      'Static protected bootstrap payload is stale',
    );
  });

  it('exposes check and write commands and keeps validation on check mode', async () => {
    const packageJson = JSON.parse(await readFile('package.json', 'utf8')) as {
      scripts: Record<string, string>;
    };
    expect(packageJson.scripts['nsis:bootstrap:write']).toContain('--write');
    expect(packageJson.scripts['nsis:bootstrap:check']).toContain('--check');
    expect(packageJson.scripts['nsis:compile-check']).toContain('nsis:bootstrap:check');
    expect(packageJson.scripts.validate).toContain('nsis:compile-check');
  });
});
